FROM node:6.6.0

RUN npm install -g weex-toolkit

WORKDIR /opt

EXPOSE 8081 8082

#RUN weex init

#RUN npm install

#RUN npm install weex-components



# http://192.168.7.61:8081/weex_tmp/h5_render/?hot-reload_controller&page=main.js&loader=xhr